let eventDay=1;
const $=s=>document.querySelector(s);
const $$=s=>Array.from(document.querySelectorAll(s));
const escapeHtml=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const img=e=>`assets/${e.image}.jpg`;
function toast(text){$('#toast').textContent=text;$('#toast').style.display='block';clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>$('#toast').style.display='none',4500)}
function renderEvents(){const query=$('#event-search').value.toLowerCase().trim();const list=eventData.filter(e=>e.day===eventDay&&`${e.name} ${e.description} ${e.topics.join(' ')}`.toLowerCase().includes(query));$('#event-grid').innerHTML=list.length?list.map(e=>`<article class="event-card reveal"><div class="card-image"><img src="${img(e)}" alt="Illustrative ${e.name.toLowerCase()} photo" loading="lazy"><span class="card-tag">${e.category}</span><span class="card-num">${String(eventData.indexOf(e)+1).padStart(2,'0')}</span></div><div class="card-body"><h3>${e.name}</h3><p>${e.description}</p><div class="card-info"><div><span>OCT 0${e.day+5} · ${e.start}</span><span>₹${e.fee} / ${e.team===1?'person':'team'}</span></div><div><span>${e.venue}</span><span>${e.team===1?'Solo':`Up to ${e.team} members`}</span></div></div><div class="card-coordinator">${e.coordinator} · +91 XXXXX XXXXX</div><div class="card-actions"><button data-detail="${e.id}" aria-label="View details for ${e.name}">View details ↗</button><button data-register="${e.id}" aria-label="Register for ${e.name}">Register →</button></div></div></article>`).join(''):'<p class="empty">No events found on this day. Try another name or switch days.</p>'}
function selectDay(day){eventDay=day;$$('[data-event-day]').forEach(b=>b.setAttribute('aria-selected',String(Number(b.dataset.eventDay)===day)));renderEvents()}
function openEvent(id){const e=eventData.find(e=>e.id===id);if(!e)return;$('#event-detail').innerHTML=`<img class="detail-image" src="${img(e)}" alt="Demo ${e.name} image"><div class="detail-body"><div class="eyebrow orange">DAY 0${e.day} / ${e.category}</div><h2>${e.name}</h2><p class="demo-note">Demo event information — final details to be confirmed.</p><div class="detail-meta"><div><span>DATE</span>October ${e.day+5}, 2026</div><div><span>TIME · IST</span>${e.time}</div><div><span>VENUE</span>${e.venue}</div><div><span>DEMO FEE</span>₹${e.fee} / ${e.team===1?'person':'team'}</div><div><span>TEAM SIZE</span>${e.team===1?'Individual':`1–${e.team} members`}</div><div><span>STATUS</span>Registration preview</div></div><h3>About the event</h3><p>${e.about}</p><h3>Topics & focus</h3><div class="topics">${e.topics.map(t=>`<span>${t}</span>`).join('')}</div><h3>How it works</h3><ol>${e.rules.map(r=>`<li>${r}</li>`).join('')}<li>The judges’ decisions are final.</li></ol><h3>Your event coordinators</h3><p>Faculty: Demo Faculty Coordinator<br>Student: ${e.coordinator} · +91 XXXXX XXXXX<br>Student: Demo Support Coordinator · +91 XXXXX XXXXX</p><div class="contact-buttons"><button disabled>Call · Coming soon</button><button disabled>WhatsApp · Coming soon</button></div><button class="button detail-register" data-register="${e.id}">Register for ${e.name} ↗</button></div>`;$('#event-dialog').showModal()}
function renderSchedule(day){const list=eventData.filter(e=>e.day===day).map(e=>({time:e.start,title:e.name,venue:e.venue,id:e.id}));list.push({time:'09:00 AM',title:'Registration & check-in',venue:'Reception desk'},{time:'09:30 AM',title:day===1?'Inauguration':'Day 2 welcome',venue:'Main Auditorium'},{time:'12:30 PM',title:'Lunch break',venue:'Campus Cafeteria'},{time:'04:30 PM',title:day===1?'Day 1 wrap-up':'Awards & closing ceremony',venue:'Main Auditorium'});const minutes=t=>{let [h,m]=t.slice(0,5).split(':').map(Number);return(h%12+(t.includes('PM')?12:0))*60+m};list.sort((a,b)=>minutes(a.time)-minutes(b.time));$('#timeline').innerHTML=list.map(e=>`<div class="timeline-item"><time>${e.time}</time><div><h3>${e.title}</h3><p>${e.venue} · Demo venue</p></div>${e.id?`<button data-detail="${e.id}" aria-label="View ${e.title}">↗</button>`:'<span>·</span>'}</div>`).join('');$$('[data-schedule-day]').forEach(b=>b.setAttribute('aria-selected',String(Number(b.dataset.scheduleDay)===day)))}
function registrationEvents(id){const day=Number($('#registration-day').value);$('#registration-event').innerHTML=eventData.filter(e=>e.day===day).map(e=>`<option value="${e.id}">${e.name}</option>`).join('');if(id)$('#registration-event').value=id;updateTeam()}
function updateTeam(){const e=eventData.find(e=>e.id===$('#registration-event').value);$('#team-members').max=e.team;if(Number($('#team-members').value)>e.team)$('#team-members').value=e.team;$('#event-fee').textContent=`Demo fee: ₹${e.fee} per ${e.team===1?'person':'team'}. Maximum ${e.team} participant${e.team>1?'s':''}. No payment is needed for this preview.`;$('#form-status').textContent=''}
function startRegistration(id){const e=eventData.find(e=>e.id===id);if(!e)return;if($('#event-dialog').open)$('#event-dialog').close();$('#registration-day').value=e.day;registrationEvents(id);$('#register').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});setTimeout(()=>$('#registration-form input').focus({preventScroll:true}),400)}
function countdown(){const diff=Math.max(0,new Date('2026-10-06T09:00:00+05:30').getTime()-Date.now());const total=Math.floor(diff/1000);$('#days').textContent=String(Math.floor(total/86400)).padStart(2,'0');$('#hours').textContent=String(Math.floor(total%86400/3600)).padStart(2,'0');$('#minutes').textContent=String(Math.floor(total%3600/60)).padStart(2,'0');$('#seconds').textContent=String(total%60).padStart(2,'0');if(diff===0)$('.count-label').textContent='THE WAIT IS OVER'}
$('#featured-grid').innerHTML=['paper','expo','robo'].map(id=>{const e=eventData.find(e=>e.id===id);return`<button class="feature-card" data-detail="${e.id}"><img src="${img(e)}" alt="${e.name} demo photograph" loading="lazy"><div><small>DAY 0${e.day} / FEATURED CHALLENGE</small><h3>${e.name}</h3><span>Discover the challenge ↗</span></div></button>`}).join('');
$('#gallery-grid').innerHTML=galleryData.map(([file,title],i)=>`<button data-gallery="${i}" aria-label="Enlarge photo: ${title}"><img src="assets/${file}.jpg" alt="${title} — demo stock photo" loading="lazy"><span>${title} ↗</span></button>`).join('');
$('#crew-grid').innerHTML=[['DF','Demo Faculty Lead','FACULTY COORDINATOR'],['FC','Demo Faculty Advisor','FACULTY COORDINATOR'],['SC','Demo Student Lead','STUDENT COORDINATOR'],['EC','Demo Events Lead','STUDENT COORDINATOR']].map(([initial,name,role])=>`<article class="crew-card"><div class="crew-avatar" aria-label="Placeholder profile">${initial}</div><small>${role}</small><h3>${name}</h3><p>Department of ECE</p><p>+91 XXXXX XXXXX</p><p>resonix2026@example.com</p><button disabled>WhatsApp · Coming soon</button></article>`).join('');
$('#faq-list').innerHTML=faqData.map(([q,a])=>`<details><summary>${q}</summary><p>${a}</p></details>`).join('');
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.detail)openEvent(b.dataset.detail);if(b.dataset.register)startRegistration(b.dataset.register);if(b.dataset.eventDay)selectDay(Number(b.dataset.eventDay));if(b.dataset.scheduleDay)renderSchedule(Number(b.dataset.scheduleDay));if(b.dataset.gallery!==undefined){const [file,title]=galleryData[Number(b.dataset.gallery)];$('#lightbox-image').src=`assets/${file}.jpg`;$('#lightbox-image').alt=`${title} — demo stock photo`;$('#lightbox-caption').textContent=`${title} · Illustrative photography, not a past RESONIX event`;$('#lightbox').showModal()}if(b.classList.contains('dialog-close'))b.closest('dialog').close();if(b.dataset.coming)toast(`${b.dataset.coming} details will be added when the college confirms its official account.`)});
$$('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}}));
$('.menu').addEventListener('click',()=>{const open=$('#nav').classList.toggle('open');$('.menu').setAttribute('aria-expanded',String(open));$('.menu').setAttribute('aria-label',open?'Close navigation':'Open navigation')});$$('#nav a').forEach(a=>a.addEventListener('click',()=>{$('#nav').classList.remove('open');$('.menu').setAttribute('aria-expanded','false')}));
$$('[role=tablist]').forEach(group=>group.addEventListener('keydown',e=>{if(!['ArrowRight','ArrowLeft','Home','End'].includes(e.key))return;e.preventDefault();const tabs=Array.from(group.querySelectorAll('[role=tab]'));let i=tabs.indexOf(document.activeElement);i=e.key==='Home'?0:e.key==='End'?tabs.length-1:(i+(e.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;tabs[i].focus();tabs[i].click()}));
$('#event-search').addEventListener('input',renderEvents);$('#registration-day').addEventListener('change',()=>registrationEvents());$('#registration-event').addEventListener('change',updateTeam);
$('#payment-file').addEventListener('change',()=>{const input=$('#payment-file'),f=input.files[0];input.setCustomValidity(f&&(f.size>5*1024*1024||!['image/png','image/jpeg','image/webp'].includes(f.type))?'Choose a PNG, JPG or WebP file under 5 MB.':'');input.reportValidity()});
$('#registration-form').addEventListener('submit',e=>{e.preventDefault();const form=e.currentTarget;if(!form.reportValidity())return;$('#form-status').textContent='Demo complete! Your entries passed validation. Nothing was sent or saved, and no place has been booked. Official registration will open later.';$('#form-status').style.color='#ffad83';toast('Demo complete — no registration or payment was submitted.')});
renderEvents();renderSchedule(1);registrationEvents();countdown();setInterval(countdown,1000);
if('IntersectionObserver'in window&&!matchMedia('(prefers-reduced-motion: reduce)').matches){const obs=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(!entry.isIntersecting)return;const el=entry.target,n=Number(el.dataset.count),start=performance.now();const tick=now=>{const t=Math.min((now-start)/1100,1);el.textContent=Math.round(n*(1-(1-t)**3))+(el.dataset.suffix||'');if(t<1)requestAnimationFrame(tick)};requestAnimationFrame(tick);obs.unobserve(el)})},{threshold:.7});$$('[data-count]').forEach(el=>obs.observe(el))}
if(document.modelContext?.registerTool){const controller=new AbortController();const tools=[{name:'list_symposium_events',description:'Read the illustrative RESONIX event lineup. Fees and schedules are demo data.',inputSchema:{type:'object',properties:{day:{type:'integer',enum:[1,2]}},additionalProperties:false},annotations:{readOnlyHint:true},execute:input=>{if(input.day!==undefined&&![1,2].includes(input.day))throw new Error('Day must be 1 or 2');return eventData.filter(e=>!input.day||e.day===input.day).map(({id,name,day,time,fee,team})=>({id,name,day,time,demoFee:fee,maximumTeamSize:team}))}},{name:'start_demo_registration',description:'Select an event and open the demo form. Does not submit or book a place.',inputSchema:{type:'object',properties:{eventId:{type:'string'}},required:['eventId'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{if(!eventData.some(e=>e.id===input.eventId))throw new Error('Unknown event');startRegistration(input.eventId);return {selectedEvent:$('#registration-event').value,status:'demo_form_open',submitted:false}}}];for(const tool of tools){try{Promise.resolve(document.modelContext.registerTool(tool,{signal:controller.signal})).catch(()=>{})}catch{}}window.addEventListener('pagehide',()=>controller.abort(),{once:true})}
